# Generated by Django 5.2.5 on 2025-12-09 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_delete_admissionsimportantdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Note title', max_length=200)),
                ('note_text', models.TextField(help_text='Note content')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for display')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admission Note',
                'verbose_name_plural': 'Admission Notes',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('new-scholar', 'New Student (Scholar)'), ('new-non-scholar', 'New Student (Non-Scholar)'), ('continuing-scholar', 'Continuing Student (Scholar)'), ('continuing-non-scholar', 'Continuing Student (Non-Scholar)')], help_text='Student category', max_length=30)),
                ('requirement_text', models.TextField(help_text='Requirement description')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for display')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admission Requirement',
                'verbose_name_plural': 'Admission Requirements',
                'ordering': ['category', 'display_order', 'requirement_text'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(help_text='Step number in the process')),
                ('title', models.CharField(help_text='Step title', max_length=200)),
                ('description', models.TextField(help_text='Step description')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for display')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enrollment Process Step',
                'verbose_name_plural': 'Enrollment Process Steps',
                'ordering': ['display_order', 'step_number'],
            },
        ),
    ]
